name = "biometrik-tts-worker" # Replace with a unique name for your worker
main = "cloudflare-worker-tts.js"
compatibility_date = "2024-05-18" # Update to today's date or a recent one

# Memastikan Wrangler tidak mencoba menggunakan Vite atau bundler lain secara otomatis
minify = true
node_compat = true

[ai]
binding = "AI"
